#!/usr/bin/env ruby

require 'Qt4'

$DEBUG = true
$VERBOSE = true

require 'pp'
require 'set'
require 'fcntl'
require 'pathname'

$:.push "lib"

require 'qasim'
require 'qasim/gui'

# QaSiM // Qt Sshfs Mapper 

Qasim::QasimGui::main

